# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

f <- system.file("uon-trial-1.csv", package = "pbwrangler")
test_that("read_workbooks works properly and show error if needed", {
  expect_error(read_workbooks(dir = NULL))
  expect_error(read_workbooks(dir = NULL, file_to_read = f, subset = TRUE))
})
