# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("my_left works properly and show error if needed", {
  expect_true(length(list_files(here::here(), subset = TRUE, n = 1)) == 1)
  expect_error(list_files(here::here(), subset = TRUE))
})

test_that("my_left works properly and show error if needed", {
  expect_true(my_left("absd", 2) == "ab")
  expect_error(my_left(112,3))
})

# Test with your dataset in "inst/"
# datafile <- system.file("nyc_squirrels_sample.csv", package = "pbwrangler")
# nyc_squirrels <- read.csv(datafile, encoding = "UTF-8")
# # Apply test on my function
# test_that("my_median works properly with internal dataset", {
#   expect_equal(my_median(nyc_squirrels[,"hectare_squirrel_number"]), 3)
# })
