# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#'  use `purrr::imap` to capture location of a trial from trial file
#'  ipurrr::map applies a function to each element of a vector and its index
#'
#' @param lst a list object
#'
#' @return a vector of same length as `lst`
#' @export
#'
#' @examples
#' f <- system.file("uon-trial-1.xlsx", package = "pbwrangler")
#' f1 <- system.file("uon-trial-1.csv", package = "pbwrangler")
#'
#' df <- read_workbooks(dir = NULL, file_to_read = f, sheet_name = "Sheet 1")
#' df1 <- read_workbooks(dir = NULL, file_to_read = f1)
#'
#' dat <- c(df, df1)
#' # this has a loc variable
#' dat_loc <- capture_location(dat)
#' lapply(dat_loc, function(x) x$loc[1:5])
capture_location <- function(lst){
  lst <- purrr::imap(
    lst, ~.x %>% dplyr::mutate(loc = gsub(
      ".*\\/|\\..*|.*it\\d+{1}_|.*at\\d+{1}_|_table|oadc.*|_at.*|_it.*|_lbht.*|_bsli.*|vegetative_|_tria.*|yield_|trial_\\d{1}_", "", .y
    ))
  )
}


#' a regular expr deleting everything after last fullstop(`.`) or last underscore(`_`)
#'
#' @param x a character vector of accession names
#'
#' @return a character vector
#' @export
#'
gen_familycode <- function(x){
  gsub("\\..*|_.*", "", x)
}

#' generate possible location from file paths
#'
#' @param x a character vector of file directory 
#'
#' @return a character vector
#' @export
#'
gen_location <- function(x){
  gsub(".*\\/|\\..*|.*it\\d+{1}_|.*at\\d+{1}_|_table|oadc.*|_at.*|_it.*|_lbht.*|_bsli.*|vegetative_|_tria.*|yield_|trial_\\d{1}_", "", x)
}
