# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' check length of accession family name - should be 9
#'
#' @param x a dataframe
#'
#' @return a data frame
#' @export
#'
check_gene_chars <- function(x){
  y <- x %>% #filter(., grepl("^CIP", geno) & nchar(gsub("\\..*|_.*", "", geno)) < 9) 
    dplyr::filter(
      .,
      # (nchar(geno) > 14 | nchar(geno) < 13) & grepl("^CIP", geno) & !grepl(".", geno)
      ((nchar(gsub("\\..*|_.*", "", geno)) < 9 | nchar(gsub("\\..*|_.*", "", geno)) > 10) & grepl("^CIP3", geno, ignore.case = T)) |
        (!grepl("^CIP3|CIP5", geno, ignore.case = T) & grepl("^cip", geno, ignore.case = T) |
           !grepl("\\.", geno) & grepl("^cip", geno, ignore.case = T))
    )
  if(dim(y)[1] >0 ){
    y <- y %>% dplyr::select(geno)
    return(y)
  }else{
    message("All accession names in order")
  }
}

#' get accession names that do not conform to required protocol
#'
#' @param x a list of dataframes
#' @param season trial season
#' @param dir output directory
#'
#' @return a data frame
#' @export
#'
#' @examples
#' f <- system.file("uon-trial-1.csv", package = "pbwrangler")
#' df <- read_workbooks(dir = NULL, file_to_read = f) 
#' df_checked <- check_geno(df)
check_geno <- function(x, season, dir = out_dir){
  out <- purrr::map(x, check_gene_chars) %>% drop_null_dfs()
  if(length(out) > 0){
    out <- out %>% capture_location() %>% dplyr::bind_rows()
    p <- file.path(dir, "data-quality-assessment",season)
    if(!dir.exists(p)) dir.create(p, recursive = TRUE)
    readr::write_csv(out, file.path(p, "wrong-accessions.csv"))
    return(out)
  }else{
    message("All accession names in order")
  }
}
