# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' clean file name using `gsub`
#'
#' @param x a character vector of file directory or file name
#'
#' @return a character vector
#' @export
#'
#' @examples
#'
#' f <- system.file("uon-trial-1.csv", package = "pbwrangler")
#' clean_dir_name(f)
clean_dir_name <- function(x){
  # delete all b4 and including /, 
  # all b4 & including dd-dd_, all after  & including.
  gsub(".*\\/", "", x) %>% gsub(".*\\d+{2}-\\d+{2}_", "", .) %>% 
    gsub("\\..*", "", .) %>% gsub("final_table|_table", "", .) %>%  
    trimws(.) %>% gsub("\\s", "-", .) %>% gsub("-{2,}", "-", .) %>%
    tolower(.) %>% gsub("-\\d{4}|_\\d{4}", "", .) %>% gsub("final-data_", "", .)
   
}

#'  clean file name using `gsub`
#'
#' @param x a character vector of file directory or file name
#'
#' @return a character vector
#' @export
#'
clean_dir_name_c <- function(x){
  gsub(".*\\/", "", x) %>% gsub("\\..*", "", .) %>% tolower(.) %>%
    gsub("-\\s+", "-",.) %>% gsub("\\s+", "-",.)
}


#' clean file names using `gsub`
#'
#' @param out a list of trial dataframes
#'
#' @return a list with names cleaned
#' @export
#'
clean_file_names <- function(out){
  names(out) <- gsub(".*\\/", "", names(out))
  return(out)
}
