# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Clean accession names
#'
#' @param x a character vector of clone/genotype IDs 
#'
#' @return a vector of same length as `x`
#' @export
#'
#' @examples
# browseURL("https://stackoverflow.com/questions/22223431/using-non-ascii-characters-inside-functions-for-packages#:~:text=R%20Portable%20packages%20must%20use,it%20refers%20to%20Unicode%20characters.")
clean_clone_name <- function(x){
  gsub("\\s+", "", x) %>%
  gsub("\\?IP|C\\u00ef\\u00bf\\u00bdP|\\u00ef\\u00bf\\\\u00bdIP|\\u00ef\\u00bf\\u00bdIP", "CIP", ., ignore.case = TRUE) %>%
  gsub("CIP31675", "CIP316375", .) %>%
  gsub("CIP314611", "CIP394611", .) %>%
  gsub("CIP317904", "CIP317004", .) %>%
  gsub("CIP 517035 517035.078", "CIP517035.078", .) %>%
  gsub("CIP517035517035.078", "CIP517035.078", .) %>%
  # change clone year from 18 to 23
    
  # gsub("CIP318", "CIP323", .) %>%
    gsub("^duct", "Dutch", .) %>%
    gsub("-filler|filler-|dummy-|-dummy", "", .)
}

