# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Compare field experiment data to see if they share designs, variables, etc.
#'
#' @param x first dataframe 
#' @param y second dataframe
#'
#' @return a dataframe with difference/similarities btwn `x`, `y`
#' @export
#'
#' @examples
#'
#' f <- system.file("uon-trial-1.csv", package = "pbwrangler")
#' df <- read_workbooks(dir=NULL, file_to_read = f)[[1]]
#' f1 <- system.file("uon-trial-1.xlsx", package = "pbwrangler")
#' df1 <- read_workbooks(dir=NULL, file_to_read = f, sheet_name = "Sheet1")[[1]]
#' compare_df(df, df1)
compare_df <- function(
    x, 
    y 
){
  out <- data.frame(
    dim_X = paste0(dim(x), collapse = ","),
    dim_Y = paste0(dim(y), collapse = ","),
    design_X = paste(max(table(x$row)), max(table(x$col)), sep = "*"),
    design_Y = paste(max(table(y$row)), max(table(y$col)), sep = "*"),
    cols_not_X = paste0(setdiff(
      union(names(x), names(y)), names(x)
    ), collapse = ","),
    cols_not_Y = paste0(setdiff(
      union(names(x), names(y)), names(y)
    ), collapse = ",")
  )
  return(out)
}
