# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' create new family code per new naming convention
#'
#' @param x a dataframe of trial data
#'
#' @return a dataframe
#' @export
#'
#' @examples
#' f <- system.file("uon-trial-1.xlsx", package = "pbwrangler")
#' df <- read_workbooks(dir = NULL, file_to_read = f, sheet_name = "Sheet 1") %>%
#'   capture_location(.) %>% `[[`(1)
#'
#' create_family_vars(df)[1:5, ]
#'
create_family_vars <- function(x){
  x %>% dplyr::select(geno, loc) %>% dplyr::mutate(
    old_family_code = my_left(geno, 9)) %>%
    dplyr::mutate(
      old_year_of_cross = ifelse(
        as.numeric(stringr::str_sub(geno, 5, 6)) > as.numeric(stringr::str_sub(lubridate::today(), 3,4)),
        paste0("19", stringr::str_sub(geno, 5, 6)),  paste0("20", stringr::str_sub(geno, 5, 6))
      ),
      year_of_cross = dplyr::case_when(
        as.numeric(stringr::str_sub(geno, 5, 6)) == 12 ~ paste0("20", 16),
        as.numeric(stringr::str_sub(geno, 5, 6)) == 13 ~ paste0("20", 17),
        as.numeric(stringr::str_sub(geno, 5, 6)) == 14 ~ paste0("20", 18),
        as.numeric(stringr::str_sub(geno, 5, 6)) == 15 ~ paste0("20", 19),
        as.numeric(stringr::str_sub(geno, 5, 6)) == 16 ~ paste0("20", 20),
        as.numeric(stringr::str_sub(geno, 5, 6)) == 17 ~ paste0("20", 21),
        as.numeric(stringr::str_sub(geno, 5, 6)) == 18 ~ paste0("20", 23),
        as.numeric(stringr::str_sub(geno, 5, 6)) > as.numeric(stringr::str_sub(lubridate::today(), 3,4)) ~ paste0("19", stringr::str_sub(geno, 5, 6)),
        TRUE ~ NA_character_
      )
    ) %>% dplyr::mutate(
      new_family_code = paste0(
        my_left(old_family_code, 4), my_right(year_of_cross, 2), my_right(old_family_code, 3)
      )
    ) %>% dplyr::mutate(
      new_clone_id = paste0(new_family_code, ".", my_right(geno, 3))
    )
}


#' create pedigree (ancestry)
#'
#' @param x a dataframe of genotypes created by `create_family_vars()`
#'
#' @return a dataframe
#' @export
#' @seealso [create_family_vars()]
#'
create_pedigree <- function(x){
  x <- x %>% dplyr::mutate(
    female = NA_character_,
    male = NA_character_
  )
}
