# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' create a meta-data file with design factors, planting dates etc
#'
#' @param x a list of trials to generate metadata for
#' @param season trial season e.g `"season-2024"`
#' @param d_dir folder directory to write the meta-data e.g., `"C://Users/Documents"`
#'
#' @return NULL
#' @export
#'
  create_meta_file <- function(x, season, d_dir = out_dir) {
  # x  is a list of trials to generate metadata for
  # season given in the form "season-2023" for example
  s <- season
  data("meta", envir = environment())
  meta[1,] <- NA
  out <- vector("list", length = length(names(x)))
  for(i in seq_along(out)) out[[i]] <- meta
  out <- out %>% magrittr::set_names(names(x))
  # year
  out <- out %>% purrr::map(
    ., ~dplyr::mutate(
      ., year = gsub("^\\w+-", "", season) %>% gsub(".*\\s+", "",.),
      # first season planting on April 1, second season planting on Nov 1
      
      planting_date = dplyr::case_when(
        str_count(s, "-") < 2 ~ as.Date(paste0("01-04-", sub("^([^-]*-[^-]*).*", "\\1", s) %>%
                                                 gsub(".*-", "",.)), format = "%d-%m-%Y"),
        TRUE ~ as.Date(paste0("01-11-", sub("^([^-]*-[^-]*).*", "\\1", s) %>%
                                gsub(".*-", "",.)), format = "%d-%m-%Y")
      ),
      # Harvesting date is 100 days post planting
      harvest_date =  dplyr::case_when(
        str_count(s, "-") < 2 ~ as.Date(paste0("01-04-",sub("^([^-]*-[^-]*).*", "\\1", s) %>%
                                                 gsub(".*-", "",.)), format = "%d-%m-%Y") + 100,
        TRUE ~ as.Date(paste0("01-11-", sub("^([^-]*-[^-]*).*", "\\1", s) %>%
                                gsub(".*-", "",.)), format = "%d-%m-%Y") + 100
      )
    )
  )
  
  out <- purrr::map(out, ~ .x %>% dplyr::mutate(location = sub("hybrid", "", sub("_.*", "", .y))))
  

  # p <- file.path(out_dir, "data", season,  "meta-data")
  p <- file.path(d_dir, "data", season,  "meta-data")
  # p_data <- file.path(out_dir, "data", season)
  if (!dir.exists(p)) {
    dir.create(p, recursive = TRUE)
    paths <- file.path(p, paste0(names(x), ".csv"))
    walk2(out, paths, write_csv)
  } else{
    # get new files
    p_sub <- setdiff(names(x), gsub("\\..*", "", list.files(p)))
    if (length(p_sub) > 0 ) {
      paths <- file.path(p, paste0(p_sub, ".csv"))
      # paths_d <- file.path(p_data, names(x), ".csv")
      walk2(out[p_sub], paths, write_csv)
    }
    
  }
  # if (!dir.exists(p_data)) {
  #   dir.create(p_data, recursive = TRUE)
  # }
  # walk2(x, paths_d, write_csv)
  }
