# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' A wrapper for `statgenSTA::createTD` for a `row-col` design model fitting
#'
#' @param x datframe of trial data
#' @param design character vector of experimental design e.g `"rowcol"`, `"rcbd"`
#'
#' @return a list object of class TD
#' @export 
#'
create_td <-  function(x, design){
  statgenSTA::createTD(
    x,
    genotype = "geno",
    trial = "trial",
    loc = "loc",
    year = "year",
    repId = "rep",
    rowCoord = "row",
    colCoord = "col",
    rowId = "row",
    colId = "col"
    ,trDesign = design
  )
}

#' extract BLUPs from a `REML` model
#'
#' @param x an object of class `STA` from `fit_td`
#' @param pred a character vector of predictors: `c("BLUEs", "seBLUEs)` or `c("BLUPs", "seBLUPs)`
#'
#' @return a dataframe
#' @export
#'
extract_blups <- function(x, pred){
  statgenSTA::STAtoTD(
    x,
    what = pred,
    keep = "trial"
  )
}



#' A wrapper for `statgenSTA::fitTD` for REML analysis
#'
#' @param x TD object generated by `create_td`
#' @param trait a character vector phenotypic traits to model e.g `ttyna`
#' @param spatial logical, whether to fit spatial structure
#'
#' @return an object of class STA
#' @export
#' @seealso [create_td()]
fit_td <- function(x, trait, spatial = FALSE){
  statgenSTA::fitTD(
    x,
    traits = trait,
    design = "res.rowcol"
    ,what = c("fixed", "random"),
    spatial = spatial
  )
}

#' Join predictor and heritability (`h2`) data objects to one dataframe
#'
#' @param x first data object either predictors or `h2`
#' @param y  second data object 
#'
#' @return a dataframe
#' @export
#'
join_by_keys <- function(x, y){
  keys <- unique(c(names(x), names(y)))
  out <- purrr::map2(
    x[keys], y[keys], dplyr::full_join
  ) %>% magrittr::set_names(keys)
  out
}
