# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' assign clones to tissue culture benches
#'
#' @param x dataframe
#' @param id_col row id index variable
#'
#' @return dataframe
#' @export
#'
assign_benches <- function(x, id_col="row_id"){
  # there are 5-rows, 5 column benches, each grid taking 192 testubes
  
  out <- x %>% dplyr::mutate(
    # Bench 1
    location = dplyr::case_when(
      .data[[id_col]] <= 192 ~ "B1R1C1",
      .data[[id_col]] <= 384 ~ "B1R1C2",
      .data[[id_col]] <= 576 ~ "B1R1C3",
      .data[[id_col]] <= 768 ~ "B1R1C4",
      .data[[id_col]] <= 960 ~ "B1R1C5",
      .data[[id_col]] <= 1152 ~ "B1R2C1",
      .data[[id_col]] <= 1344 ~ "B1R2C2",
      .data[[id_col]] <= 1536 ~ "B1R2C3",
      .data[[id_col]] <= 1728 ~ "B1R2C4",
      .data[[id_col]] <= 1920 ~ "B1R2C5",
      .data[[id_col]] <= 2112 ~ "B1R3C1",
      .data[[id_col]] <= 2304 ~ "B1R3C2",
      .data[[id_col]] <= 2496 ~ "B1R3C3",
      .data[[id_col]] <= 2688 ~ "B1R3C4",
      .data[[id_col]] <= 2880 ~ "B1R3C5",
      .data[[id_col]] <= 3072 ~ "B1R4C1",
      .data[[id_col]] <= 3264 ~ "B1R4C2",
      .data[[id_col]] <= 3456 ~ "B1R4C3",
      .data[[id_col]] <= 3648 ~ "B1R4C4",
      .data[[id_col]] <= 3840 ~ "B1R4C5",
      
      # bench 2
      
      .data[[id_col]] <= 4032 ~ "B2R1C1",
      .data[[id_col]] <= 4224 ~ "B2R1C2",
      .data[[id_col]] <= 4416 ~ "B2R1C3",
      .data[[id_col]] <= 4608 ~ "B2R1C4",
      .data[[id_col]] <= 4800 ~ "B2R1C5",
      .data[[id_col]] <= 4992 ~ "B2R2C1",
      .data[[id_col]] <= 5184 ~ "B2R2C2",
      .data[[id_col]] <= 5376 ~ "B2R2C3",
      .data[[id_col]] <= 5568 ~ "B2R2C4",
      .data[[id_col]] <= 5760 ~ "B2R2C5",
      .data[[id_col]] <= 5952 ~ "B2R3C1",
      .data[[id_col]] <= 6144 ~ "B2R3C2",
      .data[[id_col]] <= 6336 ~ "B2R3C3",
      .data[[id_col]] <= 6528 ~ "B2R3C4",
      .data[[id_col]] <= 6720 ~ "B2R3C5",
      .data[[id_col]] <= 6912 ~ "B2R4C1",
      .data[[id_col]] <= 7104 ~ "B2R4C2",
      .data[[id_col]] <= 7296 ~ "B2R4C3",
      .data[[id_col]] <= 7488 ~ "B2R4C4",
      .data[[id_col]] <= 7680 ~ "B2R4C5",
      
      # bench 3
      
      .data[[id_col]] <= 7872 ~ "B3R1C1",
      .data[[id_col]] <= 8064 ~ "B3R1C2",
      .data[[id_col]] <= 8256 ~ "B3R1C3",
      .data[[id_col]] <= 8448 ~ "B3R1C4",
      .data[[id_col]] <= 8640 ~ "B3R1C5",
      .data[[id_col]] <= 8832 ~ "B3R2C1",
      .data[[id_col]] <= 9024 ~ "B3R2C2",
      .data[[id_col]] <= 9216 ~ "B3R2C3",
      .data[[id_col]] <= 9408 ~ "B3R2C4",
      .data[[id_col]] <= 9600 ~ "B3R2C5",
      .data[[id_col]] <= 9792 ~ "B3R3C1",
      .data[[id_col]] <= 9984 ~ "B3R3C2",
      .data[[id_col]] <= 10176 ~ "B3R3C3",
      .data[[id_col]] <= 10368 ~ "B3R3C4",
      .data[[id_col]] <= 10560 ~ "B3R3C5",
      .data[[id_col]] <= 10752 ~ "B3R4C1",
      .data[[id_col]] <= 10944 ~ "B3R4C2",
      .data[[id_col]] <= 11136 ~ "B3R4C3",
      .data[[id_col]] <= 11328 ~ "B3R4C4",
      .data[[id_col]] <= 11520 ~ "B3R4C5",
      
      # bench 4
      
      .data[[id_col]] <= 11712 ~ "B4R1C1",
      .data[[id_col]] <= 11904 ~ "B4R1C2",
      .data[[id_col]] <= 12096 ~ "B4R1C3",
      .data[[id_col]] <= 12288 ~ "B4R1C4",
      .data[[id_col]] <= 12480 ~ "B4R1C5",
      .data[[id_col]] <= 12672 ~ "B4R2C1",
      .data[[id_col]] <= 12864 ~ "B4R2C2",
      .data[[id_col]] <= 13056 ~ "B4R2C3",
      .data[[id_col]] <= 13248 ~ "B4R2C4",
      .data[[id_col]] <= 13440 ~ "B4R2C5",
      .data[[id_col]] <= 13632 ~ "B4R3C1",
      .data[[id_col]] <= 13824 ~ "B4R3C2",
      .data[[id_col]] <= 14016 ~ "B4R3C3",
      .data[[id_col]] <= 14208 ~ "B4R3C4",
      .data[[id_col]] <= 14400 ~ "B4R3C5",
      .data[[id_col]] <= 14592 ~ "B4R4C1",
      .data[[id_col]] <= 14784 ~ "B4R4C2",
      .data[[id_col]] <= 14976 ~ "B4R4C3",
      .data[[id_col]] <= 15168 ~ "B4R4C4",
      .data[[id_col]] <= 15360 ~ "B4R4C5",
      
      # bench 5
      
      .data[[id_col]] <= 15552 ~ "B5R1C1",
      .data[[id_col]] <= 15744 ~ "B5R1C2",
      .data[[id_col]] <= 15936 ~ "B5R1C3",
      .data[[id_col]] <= 16128 ~ "B5R1C4",
      .data[[id_col]] <= 16320 ~ "B5R1C5",
      .data[[id_col]] <= 16512 ~ "B5R2C1",
      .data[[id_col]] <= 16704 ~ "B5R2C2",
      .data[[id_col]] <= 16896 ~ "B5R2C3",
      .data[[id_col]] <= 17088 ~ "B5R2C4",
      .data[[id_col]] <= 17280 ~ "B5R2C5",
      .data[[id_col]] <= 17472 ~ "B5R3C1",
      .data[[id_col]] <= 17664 ~ "B5R3C2",
      .data[[id_col]] <= 17856 ~ "B5R3C3",
      .data[[id_col]] <= 18048 ~ "B5R3C4",
      .data[[id_col]] <= 18240 ~ "B5R3C5",
      .data[[id_col]] <= 18432 ~ "B5R4C1",
      .data[[id_col]] <= 18624 ~ "B5R4C2",
      .data[[id_col]] <= 18816 ~ "B5R4C3",
      .data[[id_col]] <= 19008 ~ "B5R4C4",
      .data[[id_col]] <= 19200 ~ "B5R4C5",
      TRUE ~ NA_character_
    )
  )
  out <- out %>% dplyr::mutate(
    bench = substr(location, 1, 2),
    row = substr(location, 3, 4),
    col = substr(location, 5, 6)
  ) %>% dplyr::select(-dplyr::any_of(id_col)) %>% dplyr::select(unique_id, geno, dplyr::everything()) %>% 
    dplyr::arrange(location , geno)
  return(out)
}

#'  duplicate a row
#'
#' @param x a dataframe
#' @param n number of copies to create
#'
#' @return a dataframe
#' @export
#'
duplicate_row <- function(x, n = 8){
  to_add <- n - nrow(x)
  a <- x[1,]
  x_copy <- a[rep(seq_len(nrow(a)), each = to_add), ]
  out <- rbind(x, x_copy)
  return(out)
}

#' generate unique ids
#'
#' @param x a dataframe
#'
#' @return a character vector of hashed ids
#' @export
#'
gen_uniqueid <- function(x){
  n <- nrow(x)
  id <- ids::uuid(n, drop_hyphens = T ) %>% substr(., 1,12)
  return(id)
}
