# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' organize accessions to export
#'
#' @param x a list of trial dataframes for a `season`
#' @param season trial season
#' @param filename name of output file
#' @param dir  output directory
#' @param sub_dir  output sub directory
#' @return a dataframe
#' @export
#'
format_accessions <- function(
    x, 
    dir = out_dir,
    sub_dir = "accessions",
    # df = family_code,
    season, filename = "accession_miss"
    ){
  # get reference data from within the package
  # see 
  # browseURL("https://stackoverflow.com/questions/45044269/how-to-use-data-within-a-function-in-an-r-package")
  
  data("family_code", envir = environment())
  df <- family_code
  out <- capture_location(x)
  # accessions for 2023
  accessions <- purrr::reduce(out, dplyr::bind_rows) %>% dplyr::select(
    dplyr::any_of(c("geno", "loc"))
  ) %>% dplyr::distinct() %>% dplyr::mutate(season = season) %>% dplyr::filter(
    grepl("^CIP3", geno, ignore.case = TRUE)
  )

  accessions <- create_family_vars(accessions)

  # filter accession not yet in family_code
  # a = old_family_code not in family_code
  accessions_a <- accessions %>% dplyr::filter(
    old_family_code %nin% df$old_family_code
  ) %>% create_pedigree(.) %>%
    dplyr::distinct(geno, .keep_all = TRUE) %>%
    dplyr::arrange(old_family_code, geno) %>% dplyr::filter(
      geno %nin% read_accessions()$geno
    ) %>% dplyr::filter(gsub("\\..*", "", geno) %nin% family_code$new_family_code)
  # b = old_family_code in family_code
  accessions_b <- accessions %>% dplyr::filter(
    old_family_code %in% df$old_family_code
  ) %>% dplyr::arrange(old_family_code, geno)
  out_a <- list(accessions_a, accessions_b) %>% magrittr::set_names(c("acc_miss", "acc_available"))
  if(dim(out_a[[1]])[1] > 0){
    readr::write_csv(out_a[["acc_miss"]], file.path(dir, sub_dir, paste0(filename, "_", season, ".csv")))
  }
  return(out_a)
}
