# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.


#' read meta-files from separate trials in a season into 1 file
#'
#' @param season trial season such as `"season-2024"`
#' @param path directory containing meta files
#'
#' @return a dataframe
#' @export
#'
#' @examples
#'
#' list_files(system.file(package = "pbwrangler"))[1:5]
combine_meta_files <- function(season, path=out_dir){
  csv <- list.files(file.path(path, "data", season, "meta-data"), full.names = TRUE) %>%
    subset(., grepl(".csv$",.))
  if(path == m_dir){
    xls <-  list.files(file.path(path, "meta-data"), full.names = TRUE) %>%
      subset(., grepl(".xlsx$",.))
  }

  if(length(csv) > 0){
    meta <- purrr::map(files, readr::read_csv) %>% bind_rows()
  }else{
    sheets <- purrr::map(xls, readxl::excel_sheets)
    meta <- purrr::map2(xls, sheets, readxl::read_excel) %>% bind_rows()
  }
  return(meta)
}

#' get field trial fieldbooks in a particular folder
#'
#' @param path character string specifying the directory containing the fieldbooks 
#' @param season character vector of trial season
#' @param sub_folder character vector of sub-directory. defaults to NULL
#' @param s character grep pattern of file extensions to return
#'
#' @return a dataframe
#' @export
#'
get_fieldbooks <- function(path = t_dir, season, sub_folder = NULL, s = ".csv|.xlsx"){
  if(!is.null(sub_folder)){
    paths <- file.path(path, season,  sub_folder)
  }else{
    paths <- file.path(path, season)
  }
  list_files(folder = paths) %>%
    lapply(., function(x) gsub(".*\\/", "", x)) %>% 
    lapply(., function(x) subset(x, grepl(s, x))) %>%
    purrr::reduce(., c)  %>% as.data.frame() %>% `colnames<-`("filedbook") %>% 
    dplyr::mutate(
      season = season,
      sub_folder = ifelse(is.null(sub_folder), "", sub_folder)
    )
}

#' List design files after designing trial experiments in R
#'
#' @param dir directory containing the fieldboooks
#' @param season trial seasom
#' @param s a vector of charcter string to grep e.g `s = ".csv|.xlsx"`
#' @param sub_dir sub-directory if filedbooks are nested in a sub-directory
#' @param ... any other argument
#'
#' @return a list of filedbooks
#' @export
#'
  list_design_files <- function(dir = rand_dir
                                ,season = "season-2024-2025"
                                ,s = ".csv|.xlsx"
                                ,sub_dir = NULL
                                ,...) {
    if(!is.null(sub_dir)){
      files <- list.files(file.path(dir, season, sub_dir)) %>% 
        subset(., grepl(s, .)) %>% clean_dir_name_c(.) #%>% list()
    }else{
      files <- list.files(file.path(dir, season))  %>% 
        subset(., grepl(s, .)) %>% clean_dir_name_c(.) #%>% list()
    }
    out <- purrr::map(files, list) %>% magrittr::set_names(files)
    return(out)
  }

#' List file in a directory
#'
#' @param folder directory with files e.g. "C://users/user/x
#' @param subset a logical value whether or not to return a subset of files in `folder`
#' @param n integer. number of files to return if subsetting
#' @param ... any other parameters to specify
#'
#' @return a character vector of listed files
#' @export
#'
list_files <- function(folder, subset=FALSE, n = NULL, ...){
  # if(dir == t_dir){
  #   folders <- list.files(dir, full.names = TRUE) %>%
  #     # look at this subsetting `[`
  #     subset(., grepl("season", ., ignore.case = TRUE)) %>% #`[`(1:11) %>%
  #     subset(grepl(paste0(season, "$"), .))
  # }else{
  #   folders <- file <- list.files(file.path(dir, season), full.names = TRUE) 
  # }
  if(isTRUE(subset)){
    if(is.null(n)){
      stop("no of files to subset: n is NULL!")
    }else{
      files <- list.files(folder, full.names = TRUE) %>% `[`(n)
    }

  } else{
    files <- list.files(folder, full.names = TRUE)
  }
  return(files)
}
