# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Merge notes & obs to one column
#'
#' @param x a dataframe
#'
#' @return a dataframe
#' @export
#'
#' @examples
#' f <- system.file("uon-trial-1.csv", package = "pbwrangler")
#' df <- read_workbooks(dir=NULL, file_to_read = f)[[1]]
#' merge_note_obs(df)[1:5, "obs"]
merge_note_obs <- function(x){
  if("obs"%in%  names(x) & "notes" %in% names(x)){
    out <- x %>% dplyr::rowwise() %>%
      dplyr::mutate(
        obs = paste(obs, notes, sep = ",")
      ) %>% dplyr::select(-notes)
  }
  if("obs" %in% names(x) & "notes" %nin% names(x)){
    out <- x
  }
  if("obs" %nin% names(x) & "notes" %in% names(x)){
    out <- x %>% dplyr::rename(obs = notes)
  }
  if("obs" %nin% names(x) & "notes" %nin% names(x)){
    out <- x %>% dplyr::mutate(
      obs = NA_character_
    )
  }
  out <- dplyr::mutate(out, obs = as.character(obs))
  return(out)
}
