# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.


#' Extract first n elements of a string
#'
#' @param x a character vector of any length
#' @param num an integer - the number of elements to extract
#'
#' @return a character vector
#' @export
#'
#' @examples
#' a <- c("asdf", "bnmkk")
#' my_left(a, num = 3)
#'
#' a <- c("asdf", "bnmkk")
#' my_right(a, num = 3)
#'
#' df <- data.frame(a = NA, b = c(1:3, NA), c = 0)
#' drop_nas(df)
#' drop_zeros(df)
#'
my_left <- function(x,num){
  if(!is.character(x)) stop("x should be a character")
  stringr::str_sub(x, end = num)
}

#' `%nin%` returns a logical vector if there is a match or not for left operand
#'
#' @param x a vector
#' @param table a vector matching the mode of `x`
#'
#' @return logical vector
#' @export
#'
#' @examples
`%nin%` <- function(x, table){
  match(x,table, nomatch = 0) == 0
}


#' Extract last n elements of a string
#'
#'
#' @param x a character vector of any length
#' @param num an integer - the number of elements to extract
#'
#' @return a character vector
#' @export
#'
#' @examples
my_right <- function(x, num){
  if(!is.character(x)) stop("x should be a character")
  stringr::str_sub(x, start = stringr::str_length(x)-num+1)
}

#' delete columns with all values missing(`NA`)
#'
#' @param x a dataframe
#'
#' @return A dataframe without completely missing columns
#' @export
#'
#' @examples
drop_nas <- function(x){

  x[colSums(is.na(x)) < nrow(x)]
}

#' delete columns with all values 0
#'
#' @param x a dataframe
#'
#' @return a dataframe with columns with all values zero deleted
#' @export
#'
#' @examples
drop_zeros <- function(x){
  x[colSums(x == 0, na.rm = T) < nrow(x)]
} 

#' drop from a list dataframes with no dimension or  columns having all `NA`
#'
#' @param x a list of dataframes
#'
#' @return a list
#' @export
#'
#' @examples
drop_empty_dfs <- function(x){
  out <- purrr::keep(x, \(y) dim(y)[1] > 0)
  out <- purrr::map(out, drop_nas)
  return(out)
}
#' drop null dataframes from a list of dataframes
#'
#' @param x a list of dataframes
#'
#' @return a list
#' @export
#'
#' @examples
drop_null_dfs <- function(x){
  purrr::keep(x, \(y) !is.null(y))
}

#' drop dfs w/o geno column
#'
#' @param x a list of dataframes
#'
#' @return a list
#' @export
#'
#' @examples
keep_geno <- function(x){
  purrr::keep(x, \(y) "geno" %in% names(y))
}

#' drop dfs without ttyna as a column
#'
#' @param x a list
#'
#' @return a list
#' @export
#'
#' @examples
keep_ttyna <- function(x){
  purrr::keep(x, \(y) "ttyna" %in% names(y))
}


#' drop workbook sheets not of interest
#'
#' @param x a list of excel sheets
#' @param pattern patern to exclude
#'
#' @return a character vector
#' @export
#'
#' @examples
drop_sheets <- function(x, pattern = "min|pivot|sheet|weather|soil|all|unse|sele"){
  x <- unlist(x) %>% subset(., !grepl(pattern, ., ignore.case = TRUE))
  return(x)
}

#'  clean variable names
#'
#' @param x a character vector of variable names
#'
#' @return a character vector
#' @export
#'
#' @examples
clean_var_names <- function(x){
  x <- tolower(x) %>% trimws(.) %>% gsub("\\s", "_",.)
  x
}


#' sort names in ascending order
#'
#' @param x named object 
#'
#' @return null
#' @export
#'
#' @examples
names_df <- function(x){
  sort(names(x))
}


#' find variables in df
#'
#' @param x dataframe
#' @param var column name
#'
#' @return a character vector
#' @export
#'
#' @examples
find_var <- function(x, var){
  grep(paste0(var, collapse = "|"), names(x), value = TRUE)
}
# 
#' dplyr::rowwise sum target columns
#'
#' @param x a dataframe
#' @param target_cols  character vector of column names
#'
#' @return a dataframe
#' @export
#'
#' @examples
sum_rowwise <- function(x, target_cols){
  x %>% dplyr::rowwise() %>% dplyr::mutate(
    y = sum(dplyr::c_across(colnames(.)[colnames(.) %in% target_cols]),na.rm=T)
  ) %>% dplyr::pull(y)
}


#' Compute nmtp, mtwp (no/marketable tuber weight per plot)
#'
#' @param x a list of dataframes
#'
#' @return a list
#' @export
#'
#' @examples
compute_cols <- function(x){
  purrr::map(
    x, ~dplyr::mutate(
      # marketable tuber weight
      .,mtwp = sum_rowwise(., target_cols = c("mtwci", "mtwcii")),
      # number of marketable tubers
        nmtp = sum_rowwise(., target_cols = c("nmtci", "nmtcii"))
    )
  )
}
