# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.


#' Extract first n elements of a string
#'
#' @param x a character vector of any length
#' @param num an integer - the number of elements to extract
#'
#' @return a character vector
#' @export
#'
#' @examples
#' a <- c("asdf", "bnmkk")
#' my_left(a, num = 3)
#'
#' a <- c("asdf", "bnmkk")
#' my_right(a, num = 3)
#'
#' df <- data.frame(a = NA, b = c(1:3, NA), c = 0)
#' drop_nas(df)
#' drop_zeros(df)
#'
my_left <- function(x,num){
  if(!is.character(x)) stop("x should be a character")
  stringr::str_sub(x, end = num)
}

#' `%nin%` returns a logical vector if there is a match or not for left operand
#'
#' @param x a vector
#' @param table a vector matching the mode of `x`
#'
#' @return logical vector
#' @export
#'
#' @examples
`%nin%` <- function(x, table){
  match(x,table, nomatch = 0) == 0
}


#' Extract last n elements of a string
#'
#'
#' @param x a character vector of any length
#' @param num an integer - the number of elements to extract
#'
#' @return a character vector
#' @export
#'
#' @examples
my_right <- function(x, num){
  if(!is.character(x)) stop("x should be a character")
  stringr::str_sub(x, start = stringr::str_length(x)-num+1)
}

#' delete columns with all values missing(`NA`)
#'
#' @param x a dataframe
#'
#' @return A dataframe without completely missing columns
#' @export
#'
#' @examples
drop_nas <- function(x){

  x[colSums(is.na(x)) < nrow(x)]
}

#' delete columns with all values 0
#'
#' @param x a dataframe
#'
#' @return a dataframe with columns with all values zero deleted
#' @export
#'
#' @examples
drop_zeros <- function(x){
  x[colSums(x == 0, na.rm = T) < nrow(x)]
} 

#' drop from a list dataframes with no dimension or  columns having all `NA`
#'
#' @param x a list of dataframes
#'
#' @return a list
#' @export
#'
#' @examples
drop_empty_dfs <- function(x){
  out <- purrr::keep(x, \(y) dim(y)[1] > 0)
  out <- purrr::map(out, drop_nas)
  return(out)
}
#' drop null dataframes from a list of dataframes
#'
#' @param x a list of dataframes
#'
#' @return a list
#' @export
#'
#' @examples
drop_null_dfs <- function(x){
  purrr::keep(x, \(y) !is.null(y))
}

#' drop dfs w/o geno column
#'
#' @param x a list of dataframes
#'
#' @return a list
#' @export
#'
#' @examples
keep_geno <- function(x){
  purrr::keep(x, \(y) "geno" %in% names(y))
}

#' drop dfs without ttyna as a column
#'
#' @param x a list
#'
#' @return a list
#' @export
#'
#' @examples
keep_ttyna <- function(x){
  purrr::keep(x, \(y) "ttyna" %in% names(y))
}


#' drop workbook sheets not of interest
#'
#' @param x a list of excel sheets
#' @param pattern patern to exclude
#'
#' @return a character vector
#' @export
#'
#' @examples
drop_sheets <- function(x, pattern = "min|pivot|sheet|weather|soil|all|unse|sele"){
  x <- unlist(x) %>% subset(., !grepl(pattern, ., ignore.case = TRUE))
  return(x)
}

#'  clean variable names
#'
#' @param x a character vector of variable names
#'
#' @return a character vector
#' @export
#'
#' @examples
clean_var_names <- function(x){
  x <- tolower(x) %>% trimws(.) %>% gsub("\\s", "_",.)
  x
}


#' sort names in ascending order
#'
#' @param x named object 
#'
#' @return null
#' @export
#'
#' @examples
names_df <- function(x){
  sort(names(x))
}


#' find variables in df
#'
#' @param x dataframe
#' @param var column name
#'
#' @return a character vector
#' @export
#'
#' @examples
find_var <- function(x, var){
  grep(paste0(var, collapse = "|"), names(x), value = TRUE)
}
# 
#' dplyr::rowwise sum target columns
#'
#' @param x a dataframe
#' @param target_cols  character vector of column names
#'
#' @return a dataframe
#' @export
#'
#' @examples
sum_rowwise <- function(x, target_cols){
  # if(any(target_cols %in% names(x))){
  #     x %>% dplyr::rowwise() %>% dplyr::mutate(
  #   y = sum(dplyr::c_across(colnames(.)[colnames(.) %in% target_cols]),na.rm=T)
  # ) %>% dplyr::pull(y)
  # }
  rowSums(data.frame(x[,which(names(x) %in% target_cols)]),na.rm=TRUE)

}

#' split a dataframe into a list by row numbe
#'
#' @param x a dataframe
#' @param chunk integer. rows for each list element
#'
#' @return
#' @export
#'
#' @examples
split_by_chunk <- function(x, chunk) {
  n <- nrow(x)
  r  <- rep(1:ceiling(n / chunk), each = chunk)[1:n]
  d <- split(x, r)
}

#' generate rows and columns after `split_by_chunk`
#'
#' @param x a list of dataframes 
#'
#' @return a list
#' @export
#'
#' @examples
gen_row_col <- function(x){
  for(i in seq_along(x)){
    x[[i]]$row <- 1:nrow(x[[i]])
    x[[i]]$column <- i
  }
  x %>% dplyr::bind_rows()
}


#' Compute nmtp, mtwp (no/marketable tuber weight per plot)
#'
#' @param x a list of dataframes
#'
#' @return a list
#' @export
#'
#' @examples
compute_cols <- function(x) {
  
  ttwp_cols <- c("mtwci", "mtwcii", "nomtwp")
  tntp_cols <- c("nmtp", "nnomtp")
  purrr::map(
    x,
    ~ dplyr::mutate(
      # marketable tuber weight
      .,
      nmtcii = sum_rowwise(
        .,
        target_cols = c(
          "x30_35_number",
          "x35_40_number",
          "x40_45_number",
          "x45_50_number",
          "x50_55_number",
          "x55_60_number"
        )
      ),
      nmtci =
        sum_rowwise(
          .,
          target_cols = c("x60_65_number",
                          "x65_70_number", "x70_number")
        ),
      nnomtp = sum_rowwise(., target_cols = c("x0_10_number", "x10_30_number")),
      mtwci = sum_rowwise(
        .,
        target_cols = c("weight_g_60_65", "weight_g_65_70",
                        "weight_g_70")
      )/1000 ,
      mtwcii = sum_rowwise(
        .,
        target_cols = c(
          "weight_g_30_35",
          "weight_g_35_40",
          "weight_g_40_45",
          "weight_g_45_50",
          "weight_g_50_55",
          "weight_g_55_60"
        )
      )/1000 ,
      
      nomtwp = sum_rowwise(
        ., target_cols = c("weight_g_0_10",  "weight_g_10_30")
      )/1000 ,
      mtwp = sum_rowwise(., target_cols = c("mtwci", "mtwcii")),
      # number of marketable tubers
      nmtp = sum_rowwise(., target_cols = c("nmtci", "nmtcii")),
      ttwp = sum_rowwise(., target_cols = ttwp_cols),
      tntp = sum_rowwise(., target_cols = tntp_cols),
      n_tubers = sum_rowwise(., target_cols = c("nmtp", "nnomtp")),
      # pls = net plot size, pld = planting density, per 10000m^2
     pls = readr::parse_number(space_between_ridges) * 
       readr::parse_number(space_between_plants_in_ridges) #* number_of_plants_per_plot
    ,pld = 10000/pls
    ,ntp = number_of_plants_per_plot
    )
  )
}
