# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand


#' Extract first n elements of a string
#'
#' @param x a character vector of any length
#' @param num an integer - the number of elements to extract
#'
#' @return a character vector
#' @export
#'
my_left <- function(x,num){
  if(!is.character(x)) stop("x should be a character")
  stringr::str_sub(x, end = num)
}


#' Extract last n elements of a string
#'
#'
#' @param x a character vector of any length
#' @param num an integer - the number of elements to extract
#'
#' @return a character vector
#' @export
#'
#' @examples
#' a <- c("asdf", "bnmkk")
#' my_left(a, num = 3)
#'
#' a <- c("asdf", "bnmkk")
#' my_right(a, num = 3)
my_right <- function(x, num){
  if(!is.character(x)) stop("x should be a character")
  stringr::str_sub(x, start = stringr::str_length(x)-num+1)
}

