# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' run a number of checks & transformations to pre-process a list of trial data 
#'
#' @param x a list of dataframes
#'
#' @return a list of dataframes
#' @export
#'
pre_process_trials <- function(x){
  out <- keep_geno(x) %>%  purrr::map(., rename_cols) %>%
    purrr::map(., convert_to_character) %>%
    purrr::map(., merge_note_obs) %>% purrr::map(., convert_to_character) %>%
    purrr::map(., convert_to_numeric) %>%
    compute_cols(.)  %>% purrr::map(., update_geno)
   
  out <- out  %>% purrr::map(., filter_geno) %>% 
    purrr::map(
      ., ~dplyr::mutate(
        ., geno = clean_clone_name(geno)
      )
    ) %>% purrr::map(., drop_zeros) %>% 
    purrr::map(., convert_to_factor) %>%
    purrr::map(., data.frame) %>% purrr::map(., run_checks) %>% 
    clean_file_names(.)
  outt <- out %>% purrr::map(., convert_to_factor) %>% purrr::map(., data.frame)
  return(outt)
}

#' run a number of checks & transformations to pre-process a list of trial data 
#'
#' @param x a list of dataframes
#'
#' @return a list of dataframes
#' @export
#'
pre_process_trials_ <- function(x){
  out <- keep_geno(x)  %>% purrr::map(., filter_geno) %>% purrr::map(
    ., ~dplyr::mutate(
      ., geno = clean_clone_name(geno)
    ) 
  ) %>% 
    # map(., rename_cols) %>% 
    purrr::map(., data.frame) %>% purrr::map(., run_checks) %>% clean_file_names(.)

  return(out)
}

# do final processing of trials 

#' run a number of checks & transformations to pre-process a list of trial data 
#'
#' @param x a list of dataframes
#'
#' @return a list of dataframes
#' @export
#'
process_trials <- function(x){
  out <- purrr::map(x, drop_nas) %>% 
    purrr::map(., ~ dplyr::rename_with(
      .,
      ~ dplyr::case_when(
        grepl("^skin_col|predominant_tuber_skin_colour", ., ignore.case = TRUE) ~ "tbskn1",
         grepl("tuber_skin_main_colour_intensity", ., ignore.case = TRUE) ~ "tbskn2",
        grepl("^flesh_col|predominant_tuber_flesh_colour", ., ignore.case = TRUE) ~ "tbfsh1",
        grepl("secondary_tuber_flesh_colour", ., ignore.case = TRUE) ~ "tbfsh2",
        
        TRUE ~ .
      )
    )) %>% 
    
    purrr::map(
  ., ~ dplyr::mutate(
    ., n_tubers = sum_rowwise(., target_cols = c("nmtp", "nnomtp"))
  )
) %>%
    purrr::map(., convert_to_character) %>%
    purrr::map(., data.frame)
  
  return(out)
}

#' compute derived phenotypic variables 
#'
#' @param x a dataframe
#' @param sz size of farm, here taken to be 10000 sq metres
#' @param btwn spacing between ridges in metres
#' @param within spacing between plants in the same ridge in metres
#'
#' @return a dataframe
#' @export
#'
#' @examples
#' f <- system.file("uon-trial-1.csv", package = "pbwrangler")
#' df <- read_workbooks(dir = NULL, file_to_read = f)  %>%
#'   purrr::map(
#'     .,
#'     ~ dplyr::mutate(
#'       .,
#'       space_between_ridges = "0.75m",
#'       space_between_plants_in_ridges = "0.3m",
#'       number_of_plants_per_plot = 10
#'     )
#'   )
#'
#' df_out <- pre_process_trials(df) |> process_trials() %>%
#'   purrr::map(., run_data_processes)
#' purrr::map(df_out, names_df)
run_data_processes <- function(x, sz = 10000, btwn = 0.75, within = 0.3){
  x %>%  as.data.frame() %>%  st4gi::cdt(., 'np', sz/btwn/within) %>%
    st4gi::clean.data() %>% st4gi::cdt(., 'np', sz/btwn/within) %>%
    st4gi::clean.data()
}
