# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.


#' Distribute clones to match the available seeds during replication
#'
#' @param df a dataframe of available seed
#'
#' @return a list
#' @export
#'
#' @examples
#'
#' data("ilri", package = "pbwrangler")
#' ins_ilri <- geno_by_tubers(ilri)
#' lapply(ins_ilri, head, 5)
geno_by_tubers <- function(df){
  geno_3 <- df %>% dplyr::filter(number_of_tubers >= 30) %>% 
    dplyr::select(geno) %>% dplyr::pull()
  geno_2 <- df %>% dplyr::filter(number_of_tubers >= 20 & number_of_tubers < 30) %>%
    dplyr::select(geno) %>% dplyr::pull()
  geno_1 <- df %>% dplyr::filter(number_of_tubers >= 10 & number_of_tubers < 20) %>%
    dplyr::select(geno) %>% dplyr::pull()
  geno_lst <- list(geno_3, geno_2, geno_1) %>% purrr::set_names(paste0("geno_", c(3,2,1)))
  geno_names <- c(geno_3,geno_2, geno_1)
  return(geno_lst)
}

#' Partially replicated field design
#'
#' @param tot integer. total number of unique clones/genotypes to be randomized to field
#' @param ins a character vector of genotypes
#' @param rowD integer. number of rows in the field
#' @param trial character. trial name
#' @param n_dummies integer. number of dummies to complete a rectangular layout
#' @param loc character. trial location
#' @param totReps integer. total number of plots: row by col
#' @param trtrepP numeric vector. replications of `ins` given in the form 
#' `rep(c(vector of reps), c(vector of number of clones))` e.g.,
#'  `rep(c(1,8), c(304, 4))`
#' @param trtgroup numeric vector. replication of treatment groups.
#'  samilar repliction as `trtrepP` but should add to `tot`. 
#' @param block_lst a list specifying blocking of the field
#' @param season season of trial
#' @param path character specifying path to write the design
#' @param check a character vector of checks to fill rectangular grid
#' @param dummy a character vector of dummy checks to fill rectangular grid
#' @param to_add integer. number of checks to add to complete the rectangular grid
#' @return
#' @export
#'
rand_Prep <- function(tot,
                      ins,
                      rowD,
                      trial,
                      n_dummies=0,
                      loc=NULL,
                      totReps,
                      trtrepP,
                      trtgroup,
                      block_lst,
                      season = "season-2024-2025",
                      path = t_dir,
                      check = c("Shangi", "Unica", "Sagitta", "Sherekea"),
                      dummy = c("Unica", "Shangi"),
                      to_add = 4){
  # to_add <- tot - length(reduce(ins,c))

  set.seed(123456)
  if(to_add <= 4){
    checks <- sample(check, to_add, replace = F)
  }else{
    checks <- sample(check, to_add, replace = T)
  }
  
  if(n_dummies <= 2 & n_dummies > 0){
    dummies <- paste0("dummy-", sample(dummy, n_dummies, replace = F))
  }else if (n_dummies > 2) {
    dummies <- paste0("dummy-", sample(dummy, n_dummies, replace = T))
  }else{
    dummies <- NULL
  }
  geno_to_rand <- c(purrr::reduce(ins,c), dummies, checks)

  
  prep <- DiGGer::prDiGGer(
                  # numberOfTreatments = tot+n_dummies,
    # total is less 4 checks i.e all geno available + n_dummies
                  # numberOfTreatments = tot+length(checks),
                  numberOfTreatments = tot,
                   treatName = geno_to_rand,
                   rowsInDesign = rowD,
                   columnsInDesign = totReps / rowD,
                   # rowsInReplicate = 32,
                   # columnsInReplicate = 20,
                   # blockSequence = list(
                   #   c(9, 8), c(9, 4)
                   # ),
                   blockSequence = block_lst,
                   treatRepPerRep = trtrepP,
                   treatGroup=trtgroup,
                   maxInterchanges = 1000,
                   # fixedBlocks = TRUE,
                   # nested = FALSE,
                   rngSeeds = c(111, 222)
  )
  # run the search to spatially optimise the design
  design <- DiGGer::run(prep)
  
  
  # get the matrix and plot it with checks in rep
  # duplicated treatments of interest in yellow.
 fieldbook <- design$dlist[, 1:6] %>% janitor::clean_names()
  names(fieldbook)[c(1,2,5)] <- c("plot", "geno", "col")
  fieldbook <- fieldbook %>% dplyr::mutate(
    # unique_id = paste0(plot, rep, geno) 
    plot = paste0(trial, "-", stringr::str_pad(plot, 5, pad = "0"))
  ) %>% dplyr::select(plot,geno, row, col, dplyr::everything())

  if(!is.null(path)){
    png(
  file.path(path, season, "FieldBook",  paste0(trial, ".png")),
  width = 2000,
  height = 1500,
  res = 150
)
plot(design)
plot(design,
     trts = 1:5,
     col = 2,
     new = FALSE)
dev.off()
  #     readr::write_csv(
  #   design,
  #   file.path(
  #     path, season,"FieldBook",  paste0(trial, ".csv")
  #   )
  # )
        writexl::write_xlsx(list(fieldbook) %>% purrr::set_names(trial),
                     path = file.path(path, season, "FieldBook",  paste0(trial, ".xlsx")))
  
  }
  out <- list(design, fieldbook) %>% purrr::set_names(c("design", "fieldbook"))
  return(out)
}


#' generate trial design inputs i.e., geno replications and blocking list
#'
#' @param trep numeric vector of treatment/genotype replications
#' @param trgroup numeric vector of treatment group replication
#' @param block_list a list of blocking field layout 
#'
#' @return a list
#' @export
#'
#' @examples
#' d <- tempdir()
#' data("ilri", package = "pbwrangler")
#' ins_ilri <- geno_by_tubers(ilri)
#' ilri_prep <- rand_Prep(
#'   tot = 57,
#'   ins = ins_ilri,
#'   rowD = 12,
#'   trial = "KE24ILR-BIO-IT01",
#'   n_dummies = 5,
#'   loc = "ilri",
#'   totReps =96,
#'   trtrepP = trial_design_meta()$trep,
#'   trtgroup = trial_design_meta()$trgroup,
#'   block_lst = trial_design_meta()$block_list,
#'   path = NULL
#' )
#' head(ilri_prep$design)
trial_design_meta <- function(
    trep = rep(c(3,2,1,5), c(6, 11,36,4)),
    # trgroup = rep(c(3,2,1,5),c(6,11,36,4)),
    trgroup = trep,
    block_list = list(c(6,4), c(6,2))
){
    
  out <- list(
    trep, trgroup, block_list
  ) %>% purrr::set_names(c('trep', "trgroup", "block_list"))
  return(out)
}
