# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' resolvable row column design: plots = row by col; test clones replicated once, checks more than once
#'
#' @param clones a dataframe with `geno` column
#' @param tot integer. total number of unique clones/genotypes to be randomized to field
#' @param trial character. trial
#' @param rowD integer. number of rows in the field
#' @param totReps integer. total number of plots: row by col
#' @param trtrepP numeric vector. replications of `ins` given in the form 
#' `rep(c(vector of reps), c(vector of number of clones))` e.g.,
#'  `rep(c(1,8), c(304, 4))`
#' @param block_lst a list specifying blocking of the field
#' @param season season of trial
#' @param path character specifying path to write the design
#' @param check a character vector of checks to fill rectangular grid
#' @param dummy a character vector of dummy checks to fill rectangular grid
#' @param n_dummies integer. number of dummies to complete a rectangular layout
#' @param to_add integer. number of checks to add to complete the rectangular grid
#'
#' @return
#' @export
#'
#' @examples
#'
#'
#' data("ilri")
#' dat <- ilri %>% dplyr::select(geno) 
#' dat %>% dplyr::pull() 
#'
#'
#' rrc80 <- randomize_res_row_col(
#'   clones = dat,
#'   tot = 62,
#'   trial = "KE24ILR-BW-ST01",
#'   totReps = 80,
#'   trtrepP = rep(c(1, 4, 3), c(55, 4, 3)),
#'   block_lst = list(c(16,5), c(8,5)),
#'   rowD = 16,
#'   n_dummies = 3,
#'   season = "season-2025",
#'   path = NULL
#'   
#' )
#'
#' head(rrc80)
randomize_res_row_col <- function(clones,
                              tot,
                              trial,
                              totReps,
                              trtrepP,
                              # trtgroup,
                              block_lst,
                              rowD,
                              n_dummies=0,
                              # rep,
                              season,
                              path = t_dir,
                              check = c("Shangi", "Unica", "Sagitta", "Sherekea"),
                              dummy = c("Unica", "Shangi"),
                              to_add = 4) {
  if(to_add <= 4){
    checks <- sample(check, to_add, replace = F)
  }else{
    checks <- sample(check, to_add, replace = T)
  }
  
  if(n_dummies <= 2 & n_dummies > 0){
    dummies <- paste0("dummy-", sample(dummy, n_dummies, replace = F))
  }else if (n_dummies > 2) {
    dummies <- paste0("dummy-", sample(dummy, n_dummies, replace = T))
  }else{
    dummies <- NULL
  }
  
  if(inherits(clones, "list")){
    geno_names <- purrr::reduce(clones, data.frame)[, "geno"] %>% dplyr::pull()
  }else{
    geno_names <- clones %>% dplyr::pull()
  }
  geno_to_rand <- c(geno_names, dummies, checks)
  
  design <- DiGGer::corDiGGer(
    numberOfTreatments = tot,
    treatName = geno_to_rand,
    rowsInDesign = rowD,
    columnsInDesign = totReps / rowD,
    rowsInReplicate = rowD,
    columnsInReplicate = totReps / rowD,
    blockSequence = block_lst,
    treatRepPerRep = trtrepP,
    # blockSequence = list(
    #   c(5, 12), c(10, 12)
    # ),
    maxInterchanges = 500000,
    # fixedBlocks = TRUE,
    # nested = FALSE,
    rngSeeds = c(111, 222)
  )
  
  
  design <- design$dlist[, 1:6] %>% janitor::clean_names()
  colnames(design)[c(1, 2, 5)] <- c("plot", "geno", "column")
  design <- design %>% dplyr::mutate(# unique_id = paste0(plot, rep, geno)
    plot = paste0(trial, "-", stringr::str_pad(plot, 5, pad = "0"))) %>%
    dplyr::select(plot, dplyr::everything())
  if (!is.null(path)) {
    png(
      file.path(path, season, "FieldBook",  paste0(trial, ".png")),
      width = 2000,
      height = 1500,
      res = 150
    )
    plot(design)
    plot(design,
         trts = 1:5,
         col = 2,
         new = FALSE)
    dev.off()
    
    readr::write_csv(design,
                     file.path(path, season, "FieldBook",  paste0(trial, ".csv")))
  }
  return(design)
}

#' row column design: plots = row by col; equal rep for each treatment
#'
#' @param clones a dataframe with `geno` column
#' @param tot integer. total number of unique clones/genotypes to be randomized to field
#' @param trial character. trial
#' @param rowD integer. number of rows in the field
#' @param n_dummies integer. number of dummies to complete a rectangular layout
#' @param rep integer. number of replication
#' @param season season of trial
#' @param path character specifying path to write the design
#' @param check a character vector of checks to fill rectangular grid
#' @param dummy a character vector of dummy checks to fill rectangular grid
#' @param to_add integer. number of checks to add to complete the rectangular grid
#'
#' @return
#' @export
#'
#' @examples
#' df <- data.frame(geno = LETTERS[1:4])
#' rcD <-
#'   randomize_row_col(
#'     clones = df,
#'     trial = "KE24ILR-BW-ST01",
#'     tot = 6,
#'     rowD = 6,
#'     n_dummies = 0,
#'     to_add = 2,
#'     rep = 3,
#'     path = NULL
#'   )
#' head(rcD)
randomize_row_col <- function(clones,
                              tot,
                              trial,
                              rowD,
                              n_dummies=0,
                              rep,
                              season,
                              path = t_dir,
                              check = c("Shangi", "Unica", "Sagitta", "Sherekea"),
                              dummy = c("Unica", "Shangi"),
                              to_add = 4) {
  if(to_add <= 4){
    checks <- sample(check, to_add, replace = F)
  }else{
    checks <- sample(check, to_add, replace = T)
  }
  
  if(n_dummies <= 2 & n_dummies > 0){
    dummies <- paste0("dummy-", sample(dummy, n_dummies, replace = F))
  }else if (n_dummies > 2) {
    dummies <- paste0("dummy-", sample(dummy, n_dummies, replace = T))
  }else{
    dummies <- NULL
  }
  
  if(inherits(clones, "list")){
    geno_names <- purrr::reduce(clones, data.frame)[, "geno"] %>% dplyr::pull()
  }else{
    geno_names <- clones %>% dplyr::pull()
  }
  geno_to_rand <- c(geno_names, dummies, checks)
  
  design <- DiGGer::rcDiGGer(
    numberOfTreatments = tot,
    treatName = geno_to_rand,
    rowsInDesign = rowD,
    columnsInDesign = (tot * rep) / rowD,
    rowsInReplicate = tot / ((tot * rep) / rowD),
    columnsInReplicate = (tot * rep) / rowD,
    # blockSequence = list(
    #   c(5, 12), c(10, 12)
    # ),
    maxInterchanges = 500000,
    # fixedBlocks = TRUE,
    nested = FALSE,
    rngSeeds = c(111, 222)
  )
  
  
  design <- design$dlist[, 1:6] %>% janitor::clean_names()
  colnames(design)[c(1, 2, 5)] <- c("plot", "geno", "column")
  design <- design %>% dplyr::mutate(# unique_id = paste0(plot, rep, geno)
    plot = paste0(trial, "-", stringr::str_pad(plot, 5, pad = "0"))) %>% dplyr::select(plot, dplyr::everything())
  if (!is.null(path)) {
    png(
      file.path(path, season, "FieldBook",  paste0(trial, ".png")),
      width = 2000,
      height = 1500,
      res = 150
    )
    plot(design)
    plot(design,
         trts = 1:5,
         col = 2,
         new = FALSE)
    dev.off()
    
    readr::write_csv(design,
                     file.path(path, season, "FieldBook",  paste0(trial, ".csv")))
  }
  return(design)
}
