# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' randomize trials for multiplication without replication
#'
#' @param rowD integer. rows in design
#' @param tot integer. total number of genotypes
#' @param ins dataframe. contains a column named `geno`
#' @param trial character. name of trial
#' @param path character. path to write design
#' @param season character. season to randomize
#' @param to_add  integer. number of checks to add
#' @param rep integer. number of replications for each of the checks
#' @param check character. vector of checks
#' 
#' @return
#' @export
#'
#' @examples
#'
randomize_noRep <-
#'
#' data("ilri")
#' dat <- ilri %>% dplyr::select(geno) 
#'
#' d <- randomize_noRep(
#'   rowD = 11,
#'   tot = 55,
#'   ins = dat,
#'   path = NULL
#' )
#'
#' head(d)
#'
  function(rowD = 23,
           tot = 207,
           ins = ins,
           trial = "KE25MOL-HERL-ST01",
           path = t_dir,
           season = "Season 2025",
           to_add = 4,
           rep = 4,
           check = c('Sagitta', 'Unica', 'Sherekea', 'Shangi')) {
    
    set.seed(as.numeric(lubridate::today()))
    
    if(!is.null(to_add)){
      to_add_df <- data.frame(geno = rep(check, each = to_add))
      ins <- dplyr::bind_rows(ins, to_add_df)
    }
    
    fieldbook <-
      data.frame(geno = sample(ins$geno, tot, replace = FALSE))
    fieldbook$plot <- 1:nrow(fieldbook)
    fieldbook$plot <-
      paste0(trial, "-", stringr::str_pad(fieldbook$plot, 5, pad = "0"))
    
    df <- split_by_chunk(fieldbook, chunk = rowD)
    
    for (i in seq_along(df)) {
      df[[i]]$row <- 1:nrow(df[[i]])
      df[[i]]$col <- i
    }
    out <- purrr::reduce(df, dplyr::bind_rows) %>%
      dplyr::select(plot, dplyr::everything())
    
    if(!is.null(path)){
      writexl::write_xlsx(list(out) %>% purrr::set_names(trial),
                          path = file.path(path, season, "FieldBook",  paste0(trial, ".xlsx")))
    }
    return(out)
  } 

#' resolvable row column design: plots = row by col; test clones replicated once, checks more than once
#'
#' @param clones a dataframe with `geno` column
#' @param tot integer. total number of unique clones/genotypes to be randomized to field
#' @param trial character. trial
#' @param rowD integer. number of rows in the field
#' @param totReps integer. total number of plots: row by col
#' @param trtrepP numeric vector. replications of `ins` given in the form
#' `rep(c(vector of reps), c(vector of number of clones))` e.g.,
#'  `rep(c(1,8), c(304, 4))`
#' @param block_lst a list specifying blocking of the field
#' @param season season of trial
#' @param path character specifying path to write the design
#' @param check a character vector of checks to fill rectangular grid
#' @param dummy a character vector of dummy checks to fill rectangular grid
#' @param n_dummies integer. number of dummies to complete a rectangular layout
#' @param to_add integer. number of checks to add to complete the rectangular grid
#'
#' @return
#' @export
#'
#' @examples
#'
#'
#' data("ilri")
#' dat <- ilri %>% dplyr::select(geno) 
#' # dat %>% dplyr::pull() 
#'
#'
#' rrc80 <- randomize_res_row_col(
#'   clones = dat,
#'   tot = 62,
#'   trial = "KE24ILR-BW-ST01",
#'   totReps = 80,
#'   trtrepP = rep(c(1, 4, 3), c(55, 4, 3)),
#'   block_lst = list(c(16,5), c(8,5)),
#'   rowD = 16,
#'   # rowsinR = 4,
#'   # colsinR = 1,
#'   n_dummies = 3,
#'   season = "season-2025",
#'   path = NULL
#'   
#' )
#'
#' head(rrc80$fieldbook)
randomize_res_row_col <- function(clones,
                              tot,
                              trial,
                              totReps,
                              trtrepP,
                              # trtgroup,
                              block_lst,
                              rowD,
                              # rowsinR,
                              # colsinR,
                              n_dummies=0,
                              # rep,
                              season,
                              path = t_dir,
                              check = c("Shangi", "Unica", "Sagitta", "Sherekea"),
                              dummy = c("Unica", "Shangi"),
                              to_add = 4) {
  if(to_add <= 4){
    checks <- sample(check, to_add, replace = F)
  }else{
    checks <- sample(check, to_add, replace = T)
  }
  
  if(n_dummies <= 2 & n_dummies > 0){
    dummies <- paste0("dummy-", sample(dummy, n_dummies, replace = F))
  }else if (n_dummies > 2) {
    dummies <- paste0("dummy-", sample(dummy, n_dummies, replace = T))
  }else{
    dummies <- NULL
  }
  
  if(inherits(clones, "list")){
    geno_names <- purrr::reduce(clones, data.frame)[, "geno"] %>% dplyr::pull()
  }else{
    geno_names <- clones %>% dplyr::select(geno) %>%  dplyr::pull()
  }
  geno_to_rand <- c(geno_names, dummies, checks)
  
  design <- DiGGer::corDiGGer(
    numberOfTreatments = tot,
    treatName = geno_to_rand,
    rowsInDesign = rowD,
    columnsInDesign = totReps / rowD,
    rowsInReplicate = rowD,
    columnsInReplicate = totReps / rowD,
    blockSequence = block_lst,
    treatRepPerRep = trtrepP,
    # blockSequence = list(
    #   c(5, 12), c(10, 12)
    # ),
    maxInterchanges = 500000,
    # fixedBlocks = TRUE,
    # nested = FALSE,
    rngSeeds = c(111, 222)
  )
  
  
  fieldbook <- design$dlist[, 1:6] %>% janitor::clean_names()
  colnames(fieldbook)[c(1, 2, 5)] <- c("plot", "geno", "column")
  fieldbook <- fieldbook %>% dplyr::mutate(# unique_id = paste0(plot, rep, geno)
    plot = paste0(trial, "-", stringr::str_pad(plot, 5, pad = "0"))) %>%
    dplyr::select(plot, dplyr::everything())
  if (!is.null(path)) {
    png(
  file.path(path, season, "FieldBook",  paste0(trial, ".png")),
  width = 2000,
  height = 1500,
  res = 150
)
plot(design)
plot(design,
     trts = 1:5,
     col = 2,
     new = FALSE)
dev.off()
    # readr::write_csv(design,
    #                  file.path(path, season, "FieldBook",  paste0(trial, ".csv")))
        
    writexl::write_xlsx(list(fieldbook) %>% purrr::set_names(trial),
                     path = file.path(path, season, "FieldBook",  paste0(trial, ".xlsx")))
  }
  out <- list(design, fieldbook) %>% purrr::set_names(c("design", "fieldbook"))
  return(out)
}

#' row column design: plots = row by col; equal rep for each treatment
#'
#' @param clones a dataframe with `geno` column
#' @param tot integer. total number of unique clones/genotypes to be randomized to field
#' @param trial character. trial
#' @param rowD integer. number of rows in the field
#' @param rowsinR integer. number of rows in template replicate block; for blocking
#' @param colsinR integer. number of columns in template replicate block; for blocking
#' @param n_dummies integer. number of dummies to complete a rectangular layout
#' @param rep integer. number of replication
#' @param season season of trial
#' @param path character specifying path to write the design
#' @param check a character vector of checks to fill rectangular grid
#' @param dummy a character vector of dummy checks to fill rectangular grid
#' 
#' @param to_add integer. number of checks to add to complete the rectangular grid
#' \cr
#' **Note**: To optimize on the row or column, remember that rep * rowsinR = rowD or
#' rep * colsinR = colsD.
#' 
#' @return
#' @export
#'
#' @examples
#' df <- data.frame(geno = LETTERS[1:4])
#' rcD <-
#'   randomize_row_col(
#'     clones = df,
#'     trial = "KE24ILR-BW-ST01",
#'     tot = 6,
#'     rowD = 3,
#'     rowsinR = 3,
#'     colsinR = 2,
#'     n_dummies = 0,
#'     to_add = 2,
#'     rep = 3,
#'     path = NULL
#'   )
#' head(rcD$fieldbook)
randomize_row_col <- function(clones,
                              tot,
                              trial,
                              rowD,
                              rowsinR,
                              colsinR,
                              n_dummies=0,
                              rep,
                              season,
                              path = t_dir,
                              check = c("Shangi", "Unica", "Sagitta", "Sherekea"),
                              dummy = c("Unica", "Shangi"),
                              to_add = 4) {
  if(to_add <= 4){
    checks <- sample(check, to_add, replace = F)
  }else{
    checks <- sample(check, to_add, replace = T)
  }
  
  if(n_dummies <= 2 & n_dummies > 0){
    dummies <- paste0("dummy-", sample(dummy, n_dummies, replace = F))
  }else if (n_dummies > 2) {
    dummies <- paste0("dummy-", sample(dummy, n_dummies, replace = T))
  }else{
    dummies <- NULL
  }
  
  if(inherits(clones, "list")){
    geno_names <- purrr::reduce(clones, data.frame)[, "geno"] %>% dplyr::pull()
  }else{
    geno_names <- clones %>% dplyr::select(geno) %>%  dplyr::pull()
  }
  geno_to_rand <- c(geno_names, dummies, checks)
  
  design <- DiGGer::rcDiGGer(
    numberOfTreatments = tot,
    treatName = geno_to_rand,
    rowsInDesign = rowD,
    columnsInDesign = (tot * rep) / rowD,
    rowsInReplicate = rowsinR,
    columnsInReplicate = colsinR,
    # blockSequence = list(
    #   c(5, 12), c(10, 12)
    # ),
    maxInterchanges = 500000,
    # fixedBlocks = TRUE,
    nested = FALSE,
    rngSeeds = c(111, 222)
  )
  
  
 fieldbook <- design$dlist[, 1:6] %>% janitor::clean_names()
  colnames(fieldbook)[c(1, 2, 5)] <- c("plot", "geno", "column")
  fieldbook <- fieldbook %>% dplyr::mutate(# unique_id = paste0(plot, rep, geno)
    plot = paste0(trial, "-", stringr::str_pad(plot, 5, pad = "0"))) %>% dplyr::select(plot, dplyr::everything())
  if (!is.null(path)) {
png(
  file.path(path, season, "FieldBook",  paste0(trial, ".png")),
  width = 2000,
  height = 1500,
  res = 150
)
plot(design)
plot(design,
     trts = 1:5,
     col = 2,
     new = FALSE)
dev.off()
    
    # readr::write_csv(design,
    #                  file.path(path, season, "FieldBook",  paste0(trial, ".csv")))
        writexl::write_xlsx(list(fieldbook) %>% purrr::set_names(trial),
                     path = file.path(path, season, "FieldBook",  paste0(trial, ".xlsx")))
  }
  out <- list(design, fieldbook) %>% purrr::set_names(c("design", "fieldbook"))
  return(out)
}
