# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Coerce columns to character
#'
#' @param x a dataframe
#' @param to_char column names to coerce to character
#'
#' @return a dataframe
#' @export
#'
convert_to_character <- function(
    x,
    to_char =     c(
      "obs",
      "notes"
    )
    ){
  x %>% dplyr::mutate(dplyr::across(dplyr::any_of(
    to_char
  ), ~ as.character(.)))
}

#' Coerce columns to factors
#'
#' @param x a dataframe
#' @param to_fact a vector of column names to coerce to factor
#'
#' @return a dataframe
#' @export
#'
convert_to_factor <- function(
    x,
    to_fact = c(
      "rep",
      "plot",
      "loc",
      "block",
      "trial",
      "row",
      "col",
      "type",
      "check",
      "clone",
      "geno"
    )
    ){
  x %>% dplyr::mutate(dplyr::across(dplyr::any_of(
    to_fact
  ), ~ as.factor(.)))
}

#' onvert column values that numeric but read as character to numeric
#'
#' @param x a dataframe
#'
#' @return a dataframe
#' @export
#'
convert_to_numeric <- function(x){
  cols <- colnames(x[sapply(x, function(y) any(!is.na(as.numeric(y))))])
  if(length(cols) > 0){
    x[cols] <- sapply(x[cols], as.numeric)
  }
  x
}

# drop all_data
#' drop dataframe objects from a list of dataframes
#'
#' @param x a list of dataframes 
#' @param pattern pattern a character vector containing regular expression
#'
#' @return a list of dataframes
#' @export
#'
drop_all_data <- function(x, pattern ="^all|a1_table" ){
  x[!grepl(pattern, names(x))]
}

#' Filter clone ids to rid of non-compliant formats
#'
#' @param x a dataframe
#' @param pattern a character vector containing regular expression
#'
#' @return a dataframe
#' @export
#'
filter_geno <- function(x, pattern = "x|^\\*"){
  x %>% dplyr::filter(!grepl(pattern, geno, ignore.case = TRUE) & !is.na(geno))
}


#' Coarce variable to numeric or character
#'
#' @param x a dataframe
#' @param to_num columns to coerce to numeric
#' @param to_char columns to coerce to character
#'
#' @return a dataframe
#' @export
#'
#' @examples
#' f <- system.file("uon-trial-1.csv", package = "pbwrangler")
#' df <- read_workbooks(dir = NULL, file_to_read = f) %>% `[[`(1)
#' df_c <- recode_var(df)
recode_var <- function(x,
                       to_num = c("plot", "tuber_size_mm", "rep", "row", "col", "yield"),
                       to_char = c("flowering_date|obs|^note")) {
  x %>% dplyr::mutate(dplyr::across(dplyr::any_of(to_char), ~ as.character(.))
               ,
               dplyr::across(dplyr::any_of(to_num), ~ as.numeric(.)))
}

#' A wrapper for `dplyr::select` function
#'
#' @param x a dataframe
#' @param cols a character vector of column names
#'
#' @return a dataframe
#' @export
#'
select_cols <- function(x, cols){
  x %>% dplyr::select(dplyr::any_of(cols))
}
