# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' rename data columns to conform to ontology labels
#'
#' @param x a dataframe
#'
#' @return a dataframe
#' @export
#'
#' @examples
#' f <- system.file("uon-trial-1.csv", package = "pbwrangler")
#' df <- read_workbooks(dir = NULL, file_to_read = f) %>%
#'   `[[`(1)
#' df <- rename_cols(df)
rename_cols <- function(x) {
  x <- x %>%  dplyr::rename_with(
    ~ dplyr::case_when(
      grepl("column", ., ignore.case = TRUE) ~ "col",
      grepl("site|^loc", ., ignore.case = TRUE) ~ "loc",
      grepl("plot_id|plot_no|^plot", ., ignore.case = TRUE) ~ "plot",
      grepl("nph_1_present_0_absent", ., ignore.case = TRUE) ~ "nph",
      grepl("clone|^variet|instn|cip_id|^geno", ., ignore.case = TRUE) ~ "geno",
      # grepl("skin_col", ., ignore.case = TRUE) ~ "tbskn1",
      # grepl("flesh_col", ., ignore.case = TRUE) ~ "tbfsh1",
      grepl("^uniqueid|unique_id", ., ignore.case = TRUE) ~ "unique_id",
      grepl("r_audpc", ., ignore.case = TRUE) ~ "raudpc",
      grepl("s_audpc", ., ignore.case = TRUE) ~ "saudpc",
      grepl("^treat|trt", ., ignore.case = TRUE) ~ "treat",
      grepl("n_no_mtp|no_of_non_marketable|number_small_size_tubers|no_small", ., ignore.case = TRUE) ~ "nnomtp",
      grepl("weight_big_size_kg|weight_of_big|wgt_larg", ., ignore.case = TRUE) ~ "mtwci",
      grepl("weight_medium_size_kg|weight_of_medium|wgt_med", ., ignore.case = TRUE) ~ "mtwcii",
      grepl("number_big_size_tubers|no_large", ., ignore.case = TRUE) ~ "nmtci",
      grepl("number_medium_size_tubers|no_med", ., ignore.case = TRUE) ~ "nmtcii",
      grepl("no_tuber_marketable|\\bnmt\\b", ., ignore.case = TRUE) ~ "nmtp",
      grepl("wt_of_marketable_kg|mtw_kg", ., ignore.case = TRUE) ~ "mtwp",
      grepl("\\bmty\\b", ., ignore.case = TRUE) ~ "mtyna",
      grepl("tuber_yld_in_t_ha|tty_t_ha", ., ignore.case = TRUE) ~ "ttyna",
      grepl("total_tuber_weight|ttw_kg", ., ignore.case = TRUE) ~ "ttwp",
      grepl("\\btnt\\b", ., ignore.case = TRUE) ~ "tntp",
      grepl("no_mtwp|wt_of_non_marketable_kg|eight_small_size_kg|weight_of_small|wgt_small"
            , ., ignore.case = TRUE) ~ "nomtwp",
      grepl("p_vigor", ., ignore.case = TRUE) ~ "plant_vigor",
      grepl("n_emerged_plants", ., ignore.case = TRUE) ~ "npe",
      grepl("n_tubers_planted", ., ignore.case = TRUE) ~ "ntp",
      grepl("number_harvested_plants", ., ignore.case = TRUE) ~ "nph",
      grepl("senesc", ., ignore.case = TRUE) ~ "se",
      grepl("plant_height", ., ignore.case = TRUE) ~ "plahe_ev",
      grepl("main_stem_number", ., ignore.case = TRUE) ~ "snpp",
      grepl("pl_gwth", ., ignore.case = TRUE) ~ "pgh",
      grepl("inflorescence_number", ., ignore.case = TRUE) ~ "nipp",
      grepl("inflorescence_flower_number", ., ignore.case = TRUE) ~ "nfwp",
      grepl("tuber_depth_eyes", ., ignore.case = TRUE) ~ "tbshp3",
      grepl("^tuber_shape", ., ignore.case = TRUE) ~ "tbshp1",
      grepl("unusual_tuber_shape", ., ignore.case = TRUE) ~ "tbshp2",
      TRUE ~ .
    )
  )
}
