# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' run data quality checks using `{st4gi}` functions

#' @param x a dataframe
#' @param sz size of farm, here taken to be 10000 sq metres
#' @param btwn spacing between ridges in metres
#' @param within spacing between plants in the same ridge in metres
#' @param crop character. one of "sp" or "pt"
#' @param ... additional arguments
#'
#' @return a dataframe
#' @export
#'
#' @examples

#' f <- system.file("uon-trial-1.csv", package = "pbwrangler")
#' df <- read_workbooks(dir = NULL, file_to_read = f) %>%
#'   `[[`(1) %>% 
#'   dplyr::mutate(
#'           space_between_ridges = "0.75m",
#'       space_between_plants_in_ridges = "0.3m",
#'       number_of_plants_per_plot = 10
#'   )
#' df_checked <- run_checks(df)
run_checks <- function(x,sz = 10000, btwn = 0.75, within = 0.3, crop = "pt", ...){
  # check names
  y <- st4gi::check.names(x, crop = crop)
  # check outliers
  # check.data.pt(x)
  
  # compute traits
  if("spaces_between_ridges" %nin% names(x)){
      y <- st4gi::cdt(y, method = "np", sz / (within * btwn * 10), crop = crop)
  }else{
    x_btwn <- readr::parse_number(x$space_between_ridges)
    x_within <- readr::parse_number(x$space_between_plants_in_ridges)
    y <- st4gi::cdt(y, method = "np", sz / (x_within * x_btwn 
                                            # * number_of_plants_per_ridge
                                            )
                    , crop = crop)
  }

  
  # set missing values to zero
  #bug: clean.data() converts non-numeric columns to NA
  y <- st4gi::clean.data(y, crop = crop)
  # convert to CO names
  # y <- convert.co(y)
  
  return(y)
}

