# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' run data quality checks using `{st4gi}` functions

#' @param x a dataframe
#' @param sz size of farm, here taken to be 10000 sq metres
#' @param btwn spacing between ridges in metres
#' @param within spacing between plants in the same ridge in metres
#' @param ... additional arguments
#'
#' @return a dataframe
#' @export
#'
#' @examples

#' f <- system.file("uon-trial-1.csv", package = "pbwrangler")
#' df <- read_workbooks(dir = NULL, file_to_read = f) %>%
#'   `[[`(1)
#' df_checked <- run_checks(df)
run_checks <- function(x,sz = 10000, btwn = 0.75, within = 0.3,...){
  # check names
  y <- st4gi::check.names(x)
  # check outliers
  # check.data.pt(x)
  
  # compute traits
  y <- st4gi::cdt(y, method = "np", sz / (within * btwn))
  
  # set missing values to zero
  #bug: clean.data() converts non-numeric columns to NA
  y <- st4gi::clean.data(y)
  # convert to CO names
  # y <- convert.co(y)
  
  return(y)
}

