# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Title
#'
#' @return a character vector
#' @export
#'
get_design_factors <- function(){
  factors <- c("loc", "year", "season", "env", "geno", "type", 
               "rep", "block", "treat", "harvest", "is_a_control", "plot", 
               "row", "col")
  return(factors)
}

# ontology labels
#' Title
#'
#' @param x a list of dataframes or a dataframe object 
#' @param crop  a character vecto - `pt` or `sp`
#'
#' @return a dataframe
#' @export
#'
get_ontology_labels <- function(x, crop = "pt"){
  if(any(c("data.frame", "tbl", "tible_df") %in% class(x))){
    df <- names_df(x) %>% unique() %>% as.data.frame() %>% `colnames<-`('label')
  }else{
    df <- lapply(x, names_df) %>% unlist() %>% unique() %>% as.data.frame() %>%
      `colnames<-`('label')
  }
  # df$label_local <- df$label
  if(crop == "pt"){
    df_ont <- st4gi::pt.ont() %>% janitor::clean_names()
  }else{
    df_ont <- st4gi::sp.ont() %>% janitor::clean_names()
  }
  out <- df %>% dplyr::left_join(df_ont) %>% dplyr::filter(is.na(full_name))
  out <- dplyr::filter(out, !label %in% get_design_factors())
  return(out)
}

#' get column names defined in ontology
#'
#' @param x a dataframe
#'
#' @return a dataframe
#' @export
#'
get_valid_columns <- function(x){
  x[, names(x) %nin% st4gi::get_invalid_names(x)]
}

#' get invalid names (labels not in ontology) & add geno
#'
#' @param x a dataframe
#'
#' @return a dataframe
#' @export
#'
subset_invalid_cols <- function(x){
  x[,c("geno", st4gi::get_invalid_names(x))]
}
