# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Get experimental design factors from a trial dataframe/fieldbook
#'
#' @return a character vector
#' @export
#'
get_design_factors <- function(){
  factors <- c("loc", "year", "season", "env", "geno", "type", 
               "rep", "block", "treat", "harvest", "is_a_control", "plot", 
               "row", "col")
  return(factors)
}

#' get ontology labels from `{st4gi}`
#'
#' @param x a list of dataframes or a dataframe object 
#' @param crop  a character vecto - `pt` or `sp`
#'
#' @return a dataframe
#' @export
#'
get_ontology_labels <- function(x, crop = "pt"){
  if(any(c("data.frame", "tbl", "tible_df") %in% class(x))){
    df <- names_df(x) %>% unique() %>% as.data.frame() %>% `colnames<-`('label')
  }else{
    df <- lapply(x, names_df) %>% unlist() %>% unique() %>% as.data.frame() %>%
      `colnames<-`('label')
  }
  # df$label_local <- df$label
  if(crop == "pt"){
    df_ont <- st4gi::ptont() %>% janitor::clean_names()
  }else{
    df_ont <- st4gi::spont() %>% janitor::clean_names()
  }
  out <- df %>% dplyr::left_join(df_ont) %>% dplyr::filter(is.na(full_name))
  out <- dplyr::filter(out, !label %in% get_design_factors())
  return(out)
}

#' get column names defined in ontology
#'
#' @param x a dataframe
#'
#' @return a dataframe
#' @export
#'
get_valid_columns <- function(x){
  x[, names(x) %nin% st4gi::get.invalid.names(x)]
}

#' get invalid names (labels not in ontology) & add geno
#'
#' @param x a dataframe
#'
#' @return a dataframe
#' @export
#'
#' @examples
#' f <- system.file("uon-trial-1.csv", package = "pbwrangler")
#' df <- read_workbooks(dir = NULL, file_to_read = f) %>%
#'   purrr::map(
#'     ., ~dplyr::mutate(
#'       ., year = "2024", loc = "UON", trial = "lbht"
#'     )
#'   )
#' df_out <- pre_process_trials(df) |> process_trials() %>%
#'   purrr::map(., run_data_processes) %>% `[[`(1) 
#'
#' subset_invalid_cols(df_out) %>% colnames(.)
subset_invalid_cols <- function(x){
  x[,c("geno", st4gi::get.invalid.names(x))]
}
