# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' Update accession names to conform to naming convention
#'
#' @param x a dataframe
#'
#' @return a dataframe
#' @export
#'
#' @examples
#' f <- system.file("uon-trial-1.csv", package = "pbwrangler")
#' df <- read_workbooks(dir = NULL, file_to_read = f) %>%
#'   `[[`(1)
#' df_checked <- update_geno(df)
update_geno <- function(x){
  data("family_code", envir = environment())
  # family_code <- pbwrangler::family_code
  f_code <- family_code %>% dplyr::select(old_family_code, new_family_code)
    # filter(old_family_code != "NA")
  y <- x %>% dplyr::mutate(
    old_family_code = gen_familycode(geno)
  ) %>% dplyr::select(old_family_code, dplyr::everything()) 
  y <- y %>% dplyr::left_join(f_code) %>% dplyr::mutate(
      # family_code = ifelse(!is.na(new_family_code), new_family_code, old_family_code),
      geno_2 = ifelse(grepl("CIP", geno) & !is.na(new_family_code),
                  paste0(new_family_code,".", gsub(".*\\.", "", geno)), geno)
    )  %>% dplyr::select(-c("geno", "old_family_code", "new_family_code")) %>% 
    dplyr::rename(
      geno = geno_2
    ) %>% dplyr::select(geno, dplyr::everything())
  return(y)
}
