# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand # nolint: line_length_linter.

#' write processed trial data to a directory
#'
#' @param dir destination directory/folder to write to
#' @param data_list list of processed trial data
#' @param season trial season 
#'
#' @return NULL
#' @export
#'
#' @examples
#' f <- system.file("uon-trial-1.xlsx", package = "pbwrangler")
#' f1 <- system.file("uon-trial-1.csv", package = "pbwrangler")
#'
#' df <- read_workbooks(dir = NULL, file_to_read = f, sheet_name = "Sheet 1")
#' df1 <- read_workbooks(dir = NULL, file_to_read = f1)
#' dat <- c(df, df1)
#'
#' write_data(dir = tempdir(), data_list = dat, season = "season-2024")
write_data <- function(dir = b_out_dir, data_list, season){
  sn_dir <- file.path(dir, season)
  if(!exists(sn_dir)) dir.create(sn_dir, recursive = TRUE)
  paths <- file.path(sn_dir, paste0(names(data_list), ".xlsx"))
  purrr::walk2(data_list, paths, writexl::write_xlsx)
}

#' Write out data for pre-processed experimental data by calling `write_trials()`
#'
#' @param list_df a list of data frames
#' @param season seasson of experiments
#'
#' @return NULL
#' @export
#' @seealso [write_trials()]
write_season_data <- function(list_df, season){
  cat("Writing data for: ", season, "!\n")
  
  # get in/valid columns ------------------------------------------------------
  
  invalid <- purrr::map(list_df, subset_invalid_cols)
  valid <- purrr::map(list_df, get_valid_columns)
  
  
  # check accession names if in order ---------------------------------------
  
  check_geno(x = list_df, season = season)
  
  
  # save trials -------------------------------------------------------------
  
  write_trials(valid, season = season)
  write_trials(invalid, season = season, is_invalid = TRUE)
  # #season 2023 metadata ---------------------------------------------------
  
  create_meta_file(x = list_df, season = season)
  
  # # season 2023 accessions ------------------------------------------------
  
  
  # format_accessions(x = list_df, season = season)
  
  ###########################################################################
}

#' write out trial data
#'
#' @param x list of trial data
#' @param season trial season
#' @param dir output directory 
#' @param is_invalid logical: select invalid columns not defined in crop ontology
#' 
#' @return NULL
#' @export
#'
write_trials <- function(x, season, is_invalid = FALSE, dir = t_dir){
  if(isTRUE(is_invalid)){
    p <- file.path(dir, season, "Archive", "invalid-colnames")
  }else{
    p <- file.path(dir, season, "Data")
  }
  
  if(!dir.exists(p)) dir.create(p, recursive = T)
  paths <- file.path(p, paste0(names(x), ".xlsx"))
  # paths_d <- file.path(p_data, names(x), ".csv")
  purrr::walk2(x, paths, writexl::write_xlsx)
}
